---
title: Data Preparation & Documentation
jupyter: ir
---


```{r}
suppressPackageStartupMessages({
    library(tidyverse)
    library(here)
})
options(readr.show_col_types = FALSE, readr.show_progress = FALSE)
```

## German COVID-19 Data

From Zenodo, data date: February 9 2024

```{r}
# file is big, increase timeout
options(timeout = max(300, getOption("timeout")))
download.file(
    "https://zenodo.org/records/10638065/files/Aktuell_Deutschland_SarsCov2_Infektionen.csv?download=1", here("data/raw/RKI.csv")
)
```

```{r}
rki_no_meta <- read_csv(here("data/raw/RKI.csv"))
rki_metadata <- read_csv(here("data/raw/RKI_meta.csv"))

rki_no_meta$IdLandkreis <- str_pad(
    rki_no_meta$IdLandkreis,
    5,
    "left",
    "0"
)
rki <- inner_join(rki_no_meta, rki_metadata, by = "IdLandkreis")

rki$Meldedatum <- as.Date(rki$Meldedatum)
rki$Refdatum <- as.Date(rki$Refdatum)
```

```{r}
# RKI also reports differences to yesterdays publication
# current days cases / deaths are only those where "Anzahl(Todes)Fall" is >= 0
rki[rki$NeuerFall < 0, "AnzahlFall"] <- 0
rki[rki$NeuerTodesfall < 0, "AnzahlTodesfall"] <- 0
```

```{r}
rki_county <- rki
county_cases <- NULL

berlin_ids <- 11000:11012
rki_county[rki_county$IdLandkreis %in% berlin_ids, c("Landkreis", "IdLandkreis")] <- list("LK Berlin", "11000")
county_cases <- aggregate(cbind(cases = AnzahlFall, deaths = AnzahlTodesfall) ~ Meldedatum + Bundesland + Landkreis, data = rki_county, sum)
colnames(county_cases)[1:3] <- c("reporting_date", "state", "county")
county_cases <- complete(county_cases,
    reporting_date = seq(min(reporting_date), max(reporting_date), by = "1 day"),
    nesting(state, county),
    fill = list(cases = 0, deaths = 0)
)
```

## `data/processed/RKI_county.csv`
```{r}
county_cases %>%
    inner_join(
    rbind(
        rki_metadata,
        list(IdBundesland = 11, Bundesland = "Berlin", IdLandkreis = "11000", Landkreis = "LK Berlin")
    ) %>%
    arrange(IdLandkreis), by = c("county" = "Landkreis")) %>%
    select(date = reporting_date, ags = IdLandkreis, cases, deaths) %>%
    write_csv(here("data/processed/RKI_county.csv"))
```

## `data/processed/RKI_county_weekly.csv` 
weekly incidences in each county, weeks counting Monday to Sunday
```{r}
county_cases %>%
    inner_join(
    rbind(
        rki_metadata,
        list(IdBundesland = 11, Bundesland = "Berlin", IdLandkreis = "11000", Landkreis = "LK Berlin")
    ) %>%
    arrange(IdLandkreis), by = c("county" = "Landkreis")) %>%
    select(date = reporting_date, ags = IdLandkreis, cases, deaths) %>%
    group_by(date = floor_date(date, "week", week_start = 1), ags) %>%
    summarize(cases = sum(cases), deaths=sum(deaths)) %>%
    write_csv(here("data/processed/RKI_county_weekly.csv"))
```
## 