# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dissertation',
                'doc_host': 'https://stefanheyder.github.io',
                'git_url': 'https://github.com/stefanheyder/dissertation',
                'lib_path': 'ssm4epi'},
  'syms': { 'ssm4epi.models.hospitalization': { 'ssm4epi.models.hospitalization._initial_guess': ( '4 Models/4.3 Nowcasting '
                                                                                                   'hospitalizations/model.html#_initial_guess',
                                                                                                   'ssm4epi/models/hospitalization.py'),
                                                'ssm4epi.models.hospitalization.account_for_nans': ( '4 Models/4.3 Nowcasting '
                                                                                                     'hospitalizations/model.html#account_for_nans',
                                                                                                     'ssm4epi/models/hospitalization.py'),
                                                'ssm4epi.models.hospitalization.hospitalization_model': ( '4 Models/4.3 Nowcasting '
                                                                                                          'hospitalizations/model.html#hospitalization_model',
                                                                                                          'ssm4epi/models/hospitalization.py'),
                                                'ssm4epi.models.hospitalization.make_y_nan': ( '4 Models/4.3 Nowcasting '
                                                                                               'hospitalizations/model.html#make_y_nan',
                                                                                               'ssm4epi/models/hospitalization.py'),
                                                'ssm4epi.models.hospitalization.visualize_model_fit': ( '4 Models/4.3 Nowcasting '
                                                                                                        'hospitalizations/model.html#visualize_model_fit',
                                                                                                        'ssm4epi/models/hospitalization.py')},
            'ssm4epi.models.regional_growth_factor': { 'ssm4epi.models.regional_growth_factor._P': ( '4 Models/4.2 Regional growth factor '
                                                                                                     'model/model.html#_p',
                                                                                                     'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor._call_sample_n_patched': ( '4 Models/4.2 '
                                                                                                                         'Regional growth '
                                                                                                                         'factor '
                                                                                                                         'model/model.html#_call_sample_n_patched',
                                                                                                                         'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor._initial_guess': ( '4 Models/4.2 Regional '
                                                                                                                 'growth factor '
                                                                                                                 'model/model.html#_initial_guess',
                                                                                                                 'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor._observation_model': ( '4 Models/4.2 '
                                                                                                                     'Regional growth '
                                                                                                                     'factor '
                                                                                                                     'model/model.html#_observation_model',
                                                                                                                     'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor._sample_n_patched': ( '4 Models/4.2 Regional '
                                                                                                                    'growth factor '
                                                                                                                    'model/model.html#_sample_n_patched',
                                                                                                                    'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor._state_model': ( '4 Models/4.2 Regional '
                                                                                                               'growth factor '
                                                                                                               'model/model.html#_state_model',
                                                                                                               'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.account_for_nans': ( '4 Models/4.2 Regional '
                                                                                                                   'growth factor '
                                                                                                                   'model/model.html#account_for_nans',
                                                                                                                   'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.gnll': ( '4 Models/4.2 Regional growth '
                                                                                                       'factor model/model.html#gnll',
                                                                                                       'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.growth_factor_model': ( '4 Models/4.2 '
                                                                                                                      'Regional growth '
                                                                                                                      'factor '
                                                                                                                      'model/model.html#growth_factor_model',
                                                                                                                      'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.laplace_approximation': ( '4 Models/4.2 '
                                                                                                                        'Regional growth '
                                                                                                                        'factor '
                                                                                                                        'model/model.html#laplace_approximation',
                                                                                                                        'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.log_weights': ( '4 Models/4.2 Regional '
                                                                                                              'growth factor '
                                                                                                              'model/model.html#log_weights',
                                                                                                              'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.log_weights_t': ( '4 Models/4.2 Regional '
                                                                                                                'growth factor '
                                                                                                                'model/model.html#log_weights_t',
                                                                                                                'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.make_aux': ( '4 Models/4.2 Regional growth '
                                                                                                           'factor '
                                                                                                           'model/model.html#make_aux',
                                                                                                           'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.modified_efficient_importance_sampling': ( '4 '
                                                                                                                                         'Models/4.2 '
                                                                                                                                         'Regional '
                                                                                                                                         'growth '
                                                                                                                                         'factor '
                                                                                                                                         'model/model.html#modified_efficient_importance_sampling',
                                                                                                                                         'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.par_to_theta': ( '4 Models/4.2 Regional '
                                                                                                               'growth factor '
                                                                                                               'model/model.html#par_to_theta',
                                                                                                               'ssm4epi/models/regional_growth_factor.py'),
                                                       'ssm4epi.models.regional_growth_factor.theta_to_par': ( '4 Models/4.2 Regional '
                                                                                                               'growth factor '
                                                                                                               'model/model.html#theta_to_par',
                                                                                                               'ssm4epi/models/regional_growth_factor.py')},
            'ssm4epi.models.reporting_delays': { 'ssm4epi.models.reporting_delays._initial_guess': ( '4 Models/4.1 Removing reporting '
                                                                                                     'delays and weekday '
                                                                                                     'effects/model.html#_initial_guess',
                                                                                                     'ssm4epi/models/reporting_delays.py'),
                                                 'ssm4epi.models.reporting_delays._model': ( '4 Models/4.1 Removing reporting delays and '
                                                                                             'weekday effects/model.html#_model',
                                                                                             'ssm4epi/models/reporting_delays.py'),
                                                 'ssm4epi.models.reporting_delays.account_for_nans': ( '4 Models/4.1 Removing reporting '
                                                                                                       'delays and weekday '
                                                                                                       'effects/model.html#account_for_nans',
                                                                                                       'ssm4epi/models/reporting_delays.py')},
            'ssm4epi.models.util': { 'ssm4epi.models.util.__zero_to_nan': ( '4 Models/utilities.html#__zero_to_nan',
                                                                            'ssm4epi/models/util.py'),
                                     'ssm4epi.models.util.from_consecutive_logits': ( '4 Models/utilities.html#from_consecutive_logits',
                                                                                      'ssm4epi/models/util.py'),
                                     'ssm4epi.models.util.to_consecutive_logits': ( '4 Models/utilities.html#to_consecutive_logits',
                                                                                    'ssm4epi/models/util.py'),
                                     'ssm4epi.models.util.to_log_probs': ('4 Models/utilities.html#to_log_probs', 'ssm4epi/models/util.py'),
                                     'ssm4epi.models.util.visualize_pgssm': ( '4 Models/utilities.html#visualize_pgssm',
                                                                              'ssm4epi/models/util.py')},
            'ssm4epi.patch.full_deps': { 'ssm4epi.patch.full_deps.gnll': ( '4 Models/patch_full_dependencies.html#gnll',
                                                                           'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.laplace_approximation': ( '4 '
                                                                                            'Models/patch_full_dependencies.html#laplace_approximation',
                                                                                            'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.log_weights': ( '4 Models/patch_full_dependencies.html#log_weights',
                                                                                  'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.log_weights_t': ( '4 Models/patch_full_dependencies.html#log_weights_t',
                                                                                    'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.modified_efficient_importance_sampling': ( '4 '
                                                                                                             'Models/patch_full_dependencies.html#modified_efficient_importance_sampling',
                                                                                                             'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.optimal_parameters': ( '4 '
                                                                                         'Models/patch_full_dependencies.html#optimal_parameters',
                                                                                         'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.tril': ( '4 Models/patch_full_dependencies.html#tril',
                                                                           'ssm4epi/patch/full_deps.py'),
                                         'ssm4epi.patch.full_deps.triu': ( '4 Models/patch_full_dependencies.html#triu',
                                                                           'ssm4epi/patch/full_deps.py')}}}
