# AUTOGENERATED! DO NOT EDIT! File to edit: ../10_model.ipynb.

# %% auto 0
__all__ = []

# %% ../10_model.ipynb 3
import jax.numpy as jnp
import jax.scipy as jsp
import jax
from jax import vmap, jit
import matplotlib.pyplot as plt
import matplotlib as mpl

from isssm.typing import PGSSM, GLSSMState
from jaxtyping import Array, Float

from tensorflow_probability.substrates.jax.distributions import (
    NegativeBinomial as NBinom,
)
