# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dissertation',
                'doc_host': 'https://stefanheyder.github.io',
                'git_url': 'https://github.com/stefanheyder/dissertation',
                'lib_path': 'dissertation'},
  'syms': {'dissertation.core': {'dissertation.core.foo': ('core.html#foo', 'dissertation/core.py')}}}
